/** Human-readable keyboard shortcut list shown in the Help modal. */
export const shortcuts: Array<[string, string]> = [
  ['B', 'Glitch brush'],
  ['H', 'Hand / pan tool'],
  ['S / U / J', 'Smudge / Blur / Sharpen (physical keys, Cyrillic-safe)'],
  ['E / X', 'Restore / Eraser (physical keys, Cyrillic-safe)'],
  ['G', 'Random seeded glitch stamp'],
  ['[ / ]', 'Decrease / increase brush size'],
  ['Alt + drag', 'Horizontal size / vertical damage'],
  ['Space + drag', 'Temporary pan'],
  ['Wheel', 'Zoom around pointer'],
  ['Ctrl + Z', 'Undo'],
  ['Ctrl + Shift + Z / Ctrl + Y', 'Redo'],
  ['\\', 'Hold to show original'],
  ['F', 'Fit image'],
  ['1', '100% zoom'],
  ['Enter / Escape', 'Apply / cancel preview'],
  ['Shift + click', 'Select a pixel for selection-target effects'],
  ['Delete', 'Reset glitch layer'],
];
